complete -c foto -s h -l help -d "Shows help text"
complete -c foto -s V -l version -d "Shows the current version"
complete -c foto -s t -l title -d "Sets the window title"
complete -c foto -s c -l class -d "Sets the window class"
complete -c foto -s p -l pos -d "Sets the window position"
complete -c foto -s s -l size -d "Sets the window size"
complete -c foto -s b -l bg -d "Sets the background color"
complete -c foto -s r -l hotreload -d "Reloads image when it is modified"
complete -c foto -s B -l borderless -d "Removes the window border"
complete -c foto -s u -l transparent -d "Make the windows transparency match the image transparancy"
