name: Build
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt -y install build-essential libsdl2-dev libsdl2-image-dev
      - name: Setup meson
        run: meson setup build --buildtype=release
      - name: Build Foto
        run: meson compile -C build
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: foto
          path: build/Foto
